[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
libs = ["contracts/lib"]
cache_path = "contracts/cache"
fs_permissions = [{ access = "read", path = "./contracts/out"}]
evm_version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

remappings = [
    "openzeppelin=contracts/src/Party/lib/openzeppelin-contracts",
    "solmate=contracts/src/Party/lib/solmate/src",
]